### ISSUE TITLE
[Feature Request] add world scaling

### ISSUE THREAD

**Issue by elhertz** [ZsoltMolnarrr/PowerScale#15] opened 2023-08-25 01:59 UTC
Add world scaling to increase mob levels depending on the distance from the world's spawnpoint (x,z)
In this example config below you have a zone where a mob spawning in x:500 z:500 would be a Level 5 mob
```json
  "dimensions": [
    {
      "world_matches": {
        "dimension_regex": "minecraft:overworld"
      },
      "zones": [
        {
          "zone_matches": {
            "world_scaling": {
              "enabled": true,
              "distance_from_spawn": 100
            }
          },
          "difficulty": {
            "name": "normal",
            "starting_level": 0,
            "increase_level_by": 1
          }
        }
```
_Tried making a new zone setting so it's easier to understand my suggestion_

**Comment by ZsoltMolnarrr** [comment] 2023-09-09 23:29
World specific scaling is already implemented, however it doesn't have anything to do with coordinates, because it applies to a world.
```
      "world_matches": {
        "dimension_regex": "minecraft:the_nether"
      },
      "difficulty": {
        "name": "normal",
        "level": 3
      },
```

This issue looks like a duplicate of #16 , where some kind of coordinate related scaling is requested.
Feel free to reopen if that is not the case.

**Closed as completed by ZsoltMolnarrr** 2023-09-09 23:29 UTC
